/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SYSTEM.Busqueda;
import System.PokeManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fanny Brenes
 */
public class CreateRoute extends javax.swing.JFrame {
    
    /**
     * Creates new form CreateRoute
     */
    public CreateRoute() {
        initComponents();
        int x=PokeManager.getInstance().GetLugarespreterminados().size();
         int y=PokeManager.getInstance().GetBusquedaa().size();
         for (int i=0;i<x;i++) {
             combo.addItem(PokeManager.getInstance().GetLugarespreterminados().get(i).getName());
             combo2.addItem(PokeManager.getInstance().GetLugarespreterminados().get(i).getName());
            }
          for (int s=0;s<y;s++) {
             combo.addItem(PokeManager.getInstance().GetBusquedaa().get(s).getName());
             combo2.addItem(PokeManager.getInstance().GetBusquedaa().get(s).getName());
            }
         
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        combo2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Insertar punto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Ruta a realizar"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ruta más corta (Djikstra)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combo2, 0, 176, Short.MAX_VALUE)
                                    .addComponent(combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtd)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int x = PokeManager.getInstance().GetBusquedaa().size();
    int y= PokeManager.getInstance().GetLugarespreterminados().size();
    int xnumberorigen=0;
    int ynumberorigen=0;
    int xnumberdestino=0;
    int ynumberdestino=0;
    String origen=String.valueOf(combo.getSelectedItem());
    String destino=String.valueOf(combo2.getSelectedItem());
    
         for(int i=0;i<x;i++){
             if(origen==PokeManager.getInstance().GetBusqueda(i).getName()){
              xnumberorigen=Integer.parseInt(PokeManager.getInstance().GetBusqueda(i).getX());
              ynumberorigen=Integer.parseInt(PokeManager.getInstance().GetBusqueda(i).getY());
             }
             if(destino==PokeManager.getInstance().GetBusqueda(i).getName()){
              xnumberdestino=Integer.parseInt(PokeManager.getInstance().GetBusqueda(i).getX());
              ynumberdestino=Integer.parseInt(PokeManager.getInstance().GetBusqueda(i).getY());
             }
         }
         for(int s=0;s<y;s++){
             if(origen==PokeManager.getInstance().GetPreterminado(s).getName()){
              xnumberorigen=Integer.parseInt(PokeManager.getInstance().GetPreterminado(s).getX());
              ynumberorigen=Integer.parseInt(PokeManager.getInstance().GetPreterminado(s).getY());
             }
             if(destino==PokeManager.getInstance().GetPreterminado(s).getName()){
              xnumberdestino=Integer.parseInt(PokeManager.getInstance().GetPreterminado(s).getX());
              ynumberdestino=Integer.parseInt(PokeManager.getInstance().GetPreterminado(s).getY());
             }
         }
         int xcor=xnumberorigen-xnumberdestino;
         int ycor=ynumberorigen-ynumberdestino;
         if(xcor<0){
         xcor=xcor+xcor+xcor;
         }
         if(ycor<0){
         ycor=ycor+ycor+ycor;
         }
         int resultado=(xcor*xcor)+(ycor*ycor);
         float resultado1=(float)Math.sqrt(resultado);
         int distancia=Math.round(resultado1);
         int tiempo=distancia/20;
         PokeManager.getInstance().Addroad(origen, destino, distancia,tiempo);
         String arista=PokeManager.getInstance().GetRoads();
         PokeManager.getInstance().AddArista(arista);
         DefaultTableModel model = ((DefaultTableModel) tabla.getModel());
           model.setRowCount(0);
           for(String a:PokeManager.getInstance().GetArista()){
            model.addRow(new Object[]{
            a
            });
           }
          
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     PokemonAdministration usuario = new PokemonAdministration();
        usuario.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    PokeManager.getInstance().Djikstra(String.valueOf(combo.getSelectedItem()), String.valueOf(combo2.getSelectedItem()));
    txtd.setText(PokeManager.getInstance().Djikstra(String.valueOf(combo.getSelectedItem()), String.valueOf(combo2.getSelectedItem())));// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateRoute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtd;
    // End of variables declaration//GEN-END:variables
}
