/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SYSTEM.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samoy
 */
public class PokeFamily extends javax.swing.JFrame {

    private PokemonInfo pokeinfo;

    public PokemonInfo getPokemonInfo() {
        return pokeinfo;
    }

    /**
     * Creates new form PokeFamily
     */
    public PokeFamily() {
        initComponents();

        this.pokeComboBox.addItem("Select pokemon");   //Ingresa las librarías al ComboBox.
        for (PokemonInfo poketinfo : PokeManager.getInstance().GetPoke()) {
            pokeComboBox.addItem(poketinfo.getNombre());
        }
    }

    private void refresh() {  //Actualiza los valores en la interfaz.

        String pokemonName = (String) pokeComboBox.getSelectedItem();
        if (pokeComboBox.getSelectedIndex() == 0) {
            pokemonName = null;
        }
        
        PokemonInfo newInfo = new PokemonInfo();
        newInfo.setNombre(pokemonName);

        DefaultTableModel model = ((DefaultTableModel) pokeTable.getModel());  //Ingresa los títulos y valores al JTable.
        model.setRowCount(0);
        for (PokemonInfo infoo : PokeManager.getInstance().search(newInfo)) {
            model.addRow(new Object[]{
                "Name", infoo.getNombre()
            });
            model.addRow(new Object[]{
                "Species", infoo.getEspecie()
            });
            model.addRow(new Object[]{
                "Attack", infoo.getAtaque()
            });
            model.addRow(new Object[]{
                "Defence", infoo.getDefensa()
            });
            model.addRow(new Object[]{
                "Special Attack", infoo.getAtaqueEspecial()
            });
            model.addRow(new Object[]{
                "Special Defence", infoo.getDefensaEspecial()
            });
            model.addRow(new Object[]{
                "Preevolution", infoo.getPreevolucion()
            });
            model.addRow(new Object[]{
                "Possible Evolution", infoo.getPosibleEvolucion()
            });
        }
        int r = PokeManager.getInstance().GetPoke().size();
        for (int z = 0; r > z; z++) {
            if (PokeManager.getInstance().GetPokeInt(z).getNombre().equals(pokemonName)) {
                OffstringName.setText(PokeManager.getInstance().GetPoke().get(z).getHijos().getNombre());
                z = r;
            }
        }
        for (int e = 0; r > e; e++) {
            if (PokeManager.getInstance().GetPokeInt(e).getNombre().equals(pokemonName)) {
                parentsName1.setText(PokeManager.getInstance().GetPoke().get(e).getPadre().getNombre());
                e = r;
            }
        }
        System.out.println(PokeManager.getInstance().GetRelation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pokeComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        parentsName1 = new javax.swing.JTextField();
        parentsName2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OffstringName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pokeTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pokeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokeComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("PokeFamily");

        parentsName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentsName2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Parents");

        jLabel3.setText("Offspring");

        pokeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Attributes", "Rate"
            }
        ));
        jScrollPane1.setViewportView(pokeTable);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pokeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(parentsName1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addComponent(parentsName2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(OffstringName)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pokeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(parentsName1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(parentsName2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OffstringName))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parentsName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentsName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parentsName2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Player usuario = new Player();
        usuario.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pokeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokeComboBoxActionPerformed
        refresh();
    }//GEN-LAST:event_pokeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokeFamily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokeFamily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokeFamily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokeFamily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokeFamily().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OffstringName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField parentsName1;
    private javax.swing.JTextField parentsName2;
    private javax.swing.JComboBox<String> pokeComboBox;
    private javax.swing.JTable pokeTable;
    // End of variables declaration//GEN-END:variables
}
